name: Test Konflux Image

on:
  pull_request:
    types: ["labeled"]

jobs:
  integration-tests:
    name: Fetch the image built on Konflux and run integration tests on it

    # TODO: Replace this with ubuntu-latest once GH completes the migration of the VM runners to
    # ubuntu 24.04 and respect the YAML tag (revert the commit that added this)
    runs-on: ubuntu-24.04
    env:
      HERMETO_IMAGE: quay.io/redhat-user-workloads/rh-hermeto-tenant/hermeto:on-pr-${{ github.sha }}
    steps:
      - name: Print Image
        run: |
          echo $HERMETO_IMAGE
          echo ${{ toJSON(github) }}
